# Generated by Django 5.1.1 on 2024-10-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_out_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
