# Generated by Django 5.0.4 on 2024-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_attendance_check_in_time_attendance_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mda',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
