# Generated by Django 5.0.4 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_mda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mda',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
